version: 2
updates:
  # Fetch and update latest `composer` packages
  - package-ecosystem: composer
    directory: '/'
    schedule:
      interval: daily
      time: '00:00'
    reviewers:
      - brandonlinu
    assignees:
      - brandonlinu
    commit-message:
      prefix: fix
      prefix-development: chore
      include: scope
  # Fetch and update latest `github-actions` pkgs
  - package-ecosystem: github-actions
    directory: '/'
    schedule:
      interval: daily
      time: '00:00'
    reviewers:
      - brandonlinu
    assignees:
      - brandonlinu
    commit-message:
      prefix: fix
      prefix-development: chore
      include: scope
